name: fliechart
description: A Flutter package for pie charts
version: 0.0.1
author: André Luiz Clinio (andre.clinio@gmail.com)
homepage: https://github.com/andreclinio/fliechart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

